language: node_js
cache:
  # Do not use npm cache, only yarn
  yarn
directories:
  - ./.yarn/cache
node_js:
  - 20
branches:
  only:
    # Only run with the main branch
    - main
    - /^v[0-9]+.*$/
before_install:
  # Remove existing files and folders
  - rm .yarnrc.yml
  - rm -rf node_modules
  # Install nvm, npm, check Node
  - npm install -g angular-cli
  - nvm install node
  - node -v
  - npm i -g npm@10.5.0
  # Get repo for Yarn and install
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn set version berry
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Then the local Yarn 2 should be available and get used
  - yarn -v
install:
  # Install all our dependencies
  - yarn
script:
  # Run the Jest tests to make sure it is working
  - ng test